### ISSUE TITLE
Test suite issues on different Debian release architectures

### ISSUE THREAD

**Issue by tillea** [igraph/igraph#1370]
Hi,
there is a new [bug report](https://bugs.debian.org/956821) concerning different Debian release architectures.  For example the [arm64 build log](https://buildd.debian.org/status/fetch.php?pkg=igraph&arch=arm64&ver=0.8.1%2Bds-1&stamp=1585576245&raw=0) is mentioning the following errors:

    128: Merging layouts 2 (igraph_i_layout_merge):      FAILED (layout.at:68)
    195: Infomap community structure (igraph_community_infomap) : FAILED (community.at:99)
    251: SCG of a graph, stochastic matrix (igraph_scg) : FAILED (scg.at:73)

There are even more errors on i386 architecture.  I'll try to reproduce these by emulating that architecture and will attach this in another post to this bug report.
Kind regards, Andreas.

**Comment by szhorvat** [comment]
Can you please upload the full contents of `tests/testsuite.dir`?

**Comment by tillea** [comment]
On Wed, Apr 15, 2020 at 11:44:09AM -0700, Szabolcs Horvát wrote:
> Can you please upload the full contents of `tests/testsuite.dir`?
As I tried to express: I have no access to these data of Debian autobuilders but I try to do a build on an i386 emulation and will upload the result of this (hopefully reproducing the same issues).

**Comment by tillea** [comment]
This is the build in i386 emulation.  It has the same tests failing as on the real hardware.
[i386_testsuite_dir.zip](https://github.com/igraph/igraph/files/4483267/i386_testsuite_dir.zip)

**Comment by szhorvat** [comment]
Thanks for the report Andreas!

The bug you linked seemed to suggest that these failures started to happen only with 0.8.1. That would be strange, as these functions were not touched, at least not in any meaningful way. If it is not too much trouble, could you please try the same with 0.8.0 on the very same system (same hardware, same compiler)?

**Comment by szhorvat** [comment]
Was there anything else that changed than going from igraph 0.8.0 -> 0.8.1? I assume you built igraph with all external packages (external arpack, lapack, blas, etc.) Did those dependencies change?

Since some of these look like they may be due to numerical issues, could the compiler (different compiler version or different optimizations) be at least partly responsible?

**Comment by vtraag** [comment]
This problem was already observed previously in issue #678. There, the discussion lead us to relax the testing because it does not seem to be possible to guarantee consistent output always (but feel free to suggest possibilities). We have not yet gotten around to correcting this. I presume this is necessary to be able to include the new `igraph` release in Debian? If so, we should treat this with a higher priority.

**Comment by tillea** [comment]
On Wed, Apr 15, 2020 at 12:52:06PM -0700, Vincent Traag wrote:
> This problem was already observed previously in issue #678. There, the discussion lead us to relax the testing because it does not seem to be possible to guarantee consistent output always (but feel free to suggest possibilities). We have not yet gotten around to correcting this. I presume this is necessary to be able to include the new `igraph` release in Debian? If so, we should treat this with a higher priority.
I can confirm that it really affects the Debian distribution.  The build that passed before were in 0.7.1.  If you do not change the tests the new 0.8.? series will not migrate to Debian testing and will finally not be released with the stable distribution.
Kind regards, Andreas.

**Comment by szhorvat** [comment]
@tillea A lot of the affected code was already present in 0.7.1, so it is surprising that the tests passed before, but they are failing now. If it is not too much trouble, could you please help figure out what exactly changed? I strongly suspect that it is not just igraph, but it's the way you build it (dependencies, compiler, hardware).

I can't speak for others, but personally I am stuck at home with limited access to different systems to test on, which makes it difficult to get to the bottom of the problem. Still, I tried it on whatever I could get access to.  All tests pass on:

 - macOS 10.14 with default compiler
 - Ubuntu 16.04 with default compiler (x86_64 in a VM)
 - Raspbian Buster with default compiler (32-bit ARM)
 - openSUSE Leap 15.1 with gcc 7.5.0 (x86_64 on our HPC cluster)

**Comment by tillea** [comment]
On Thu, Apr 16, 2020 at 02:40:47AM -0700, Szabolcs Horvát wrote:
> @tillea A lot of the affected code was already present in 0.7.1, so it is surprising that the tests passed before, but they are failing now. If it is not too much trouble, could you please help figure out what exactly changed? I strongly suspect that it is not just igraph, but it's the way you build it (dependencies, compiler, hardware).
> 
> I can't speak for others, but personally I am stuck at home with limited access to different systems to test on, which makes it difficult to get to the bottom of the problem. Still, I tried it on whatever I could get access to.  All tests pass on:
Speaking about me: I have my fingers in about 1000 packages in Debian.  Currently those packages that are highly relevant for COVID-19 have high priority.  I have no time to dig deeper into this issue.  If the solution is simply relaxing the testing criteria a bit (which is completely in line with your suspicion that compiler or hardware might have changed meanwhile) than please do so and we try uploading again.
Thanks a lot for your understanding, Andreas.

**Comment by ntamas** [comment]
My proposal: let's try to get this sorted out for i386 in some simulated environment (if we can reproduce this) and try the build again if it passes on i386. Maybe the relaxations that we build into the tests would also make them pass on other architectures.

@szhorvat when testing on Raspbian, did you build it with external LAPACK/ARPACK libraries? If so, did you use the official packages in Raspbian or did you use some other, alternative LAPACK/ARPACK implementation?

@tillea I don't have much experience with simulated i386 environments - is there a quickstart guide somewhere on the Debian pages that describes how to do this? I can try Virtualbox on my Mac or QEMU on an amd64-based Linux server at the university if any of these are feasible options.

**Comment by szhorvat** [comment]
@ntamas No, I didn't build with external packages. This issue is almost certainly not because of i368, but because of using external packages. I do see some failures on macOS when using *all* external packages.

**Comment by szhorvat** [comment]
It would be better to start with fixing up the tests so that they do not depend on the behaviour of the external dependencies (when those behaviours are correct). I suggest doing this first, and leaving the i386 stuff for later.

Doing this would take quite a bit of work because none of us have a full understanding of all functionality included in igraph. E.g., several of the SCG tests fail. One would need to read up on spectral coarse graining before one can understand if the failure is a true problem, or just an issue with the test being too specific.

**Comment by AdrianBunk** [comment]
> This issue is almost certainly not because of i368, but because of using external packages.

There might be several problems, and one of them is related to i386:
The Debian i386 port still supports relatively old hardware, and therefore uses only the x87 FPU.
The x87 FPU has excess precision (80bit), which can result in different floating point results.
I am getting fewer (but not 0) failures when rebuilding the Debian package with "-msse2 -mfpmath=sse".

**Comment by szhorvat** [comment]
@AdrianBunk Do you know if x87 FPU instructions are supported at all on x86_64?

On macOS, if I use [`-mfpmath=387`](https://gcc.gnu.org/onlinedocs/gcc-9.3.0/gcc/x86-Options.html), I get 

> error: the '387' unit is not supported with this instruction set

I do not know if this is a limitation of clang, a limitation of macOS, or a limitation of the x86_64 instruction set.

**Comment by ntamas** [comment]
Judging from [this page](https://buildd.debian.org/status/package.php?p=igraph&suite=sid), some problems are not related to test cases but indicate a general compilation failure (e.g., [this one](https://buildd.debian.org/status/package.php?p=igraph&suite=sid#problem-2)). It looks like on certain platforms the linker is not trying to link to the standard C++ library, which might be a misconfiguration on our end.

**Comment by szhorvat** [comment]
Split off the x87 issues into #1371

**Comment by AdrianBunk** [comment]
> Judging from [this page](https://buildd.debian.org/status/package.php?p=igraph&suite=sid), some problems are not related to test cases but indicate a general compilation failure (e.g., [this one](https://buildd.debian.org/status/package.php?p=igraph&suite=sid#problem-2)). It looks like on certain platforms the linker is not trying to link to the standard C++ library, which might be a misconfiguration on our end.

Ignore these symbol errors, this is a Debian packaging issue. Debian has a way to track what symbols a shared library provides and when they were introduced, and can generate versioned dependencies in packages using the library based on the versions when the symbols used from the library were introduced instead of enforcing a dependency on the latest version of the library.
https://sources.debian.org/src/igraph/0.8.1+ds-1/debian/libigraph1.symbols/

**Comment by AdrianBunk** [comment]
Since i386-specific problems moved elsewhere, the problem in question is:
testsuite: 128 195 251 failed

Failing architectures for that:
- arm64
- i386
- ppc*
- s390x
- ia64
- riscv64

The ppc failures alone cover big/little endian and 32/64 bit, there is no obvious pattern which architectures fail.

**Comment by szhorvat** [comment]
@tillea Small not: I believe you do not need to pass `--with-external-f2c` to `./configure` when you already have `--with-external-blas --with-external-lapack --with-external-arpack`. f2c simply won't be used.

**Comment by tillea** [comment]
On Thu, Apr 16, 2020 at 03:33:28AM -0700, Szabolcs Horvát wrote:
> @ntamas No, I didn't build with external packages. This issue is almost certainly not because of i368, but because of using external packages. I do see some failures on macOS when using *all* external packages.
Debian is definitely using all external packages that are packaged for Debian.

**Comment by tillea** [comment]
On Thu, Apr 16, 2020 at 03:18:10AM -0700, Tamás Nepusz wrote:
> My proposal: let's try to get this sorted out for i386 in some simulated environment (if we can reproduce this) and try the build again if it passes on i386. Maybe the relaxations that we build into the tests would also make them pass on other architectures.

I think this is a pretty sensible approach.
 
> @tillea I don't have much experience with simulated i386 environments - is there a quickstart guide somewhere on the Debian pages that describes how to do this? I can try Virtualbox on my Mac or QEMU on an amd64-based Linux server at the university if any of these are feasible options.

The Debian build process is usually done in a clean chroot installing those packages only that are needed for the build.  There is some way (which I forgot, sorry) to create a multiarch-i386 chroot to build for i386 on amd64 machine.  I think you are better served with QEMU (which I don't have experience with) than with such a chroot.  Let me know if I should dig for this information anyway.

Kind regards, Andreas.

**Comment by tillea** [comment]
On Thu, Apr 16, 2020 at 07:15:31AM -0700, Szabolcs Horvát wrote:
> @tillea Small note: I believe you do not need to pass `--with-external-f2c` to `./configure` when you already have `--with-external-blas --with-external-lapack --with-external-arpack`. f2c simply won't be used.
Fixed in Git.  Thanks for the hint, Andreas.

**Comment by szhorvat** [comment]
Another followup: https://github.com/igraph/igraph/issues/1372  This still doesn't cover all issues reported here.

@tillea Can you let us know the precise versions of blas, lapack, arpack you use and link to?

**Comment by AdrianBunk** [comment]
> Can you let us know the precise versions of blas, lapack, arpack you use and link to?

They are downloaded and installed at the beginning in the build logs at https://buildd.debian.org/status/package.php?p=igraph&suite=sid

```
Get:46 https://mirror.netcologne.de/debian unstable/main arm64 libblas-dev arm64 3.9.0-1 [107 kB]
Get:47 https://mirror.netcologne.de/debian unstable/main arm64 liblapack-dev arm64 3.9.0-1 [2777 kB]
Get:48 https://mirror.netcologne.de/debian unstable/main arm64 libarpack2-dev arm64 3.7.0-3 [99.5 kB]
```

**Comment by AdrianBunk** [comment]
Not sure whether it is related to any of the test failures, but some of the compile warnings in the build logs seem to point at real bugs.

```
foreign.c: In function ‘igraph_i_gml_tostring’:
foreign.c:1052:12: warning: function may return address of local variable [-Wreturn-local-addr]
 1052 |     return p;
      |            ^
foreign.c:1031:10: note: declared here
 1031 |     char tmp[256];
      |          ^~~
```

Something like this or code causing ``may be used uninitialized`` warnings can easily create the kind of bugs that appear or disappear based on random changes like compiler/architecture/optimization/...

**Comment by ntamas** [comment]
Thanks @AdrianBunk , nice catch! I'll fix this soon, although it's probably unrelated (it is triggered only when reading GML files, and none of the problematic test cases do that).

I have fixed two test case failures on my computer (for the external ARPACK case) in https://github.com/igraph/igraph/commit/e3f48fe9241a6ff97b439f58720123c07b2aebb4 and https://github.com/igraph/igraph/commit/55f88af60e7d65e158226c0328eca38b6cd539d0; these will be cherry-picked back to the master branch soon.

**Comment by ntamas** [comment]
https://github.com/igraph/igraph/commit/f03d9142577f035a878e81b0cdab334974d35d00 fixes the issue raised by @AdrianBunk ; https://github.com/igraph/igraph/commit/c7fa48790b35a5c5bcd2739ee4f177084061a454 probably fixes test case 128 (129 in the develop branch). Test case 251 is most likely fixed as well. Test case 195 seems to be unrelated to BLAS / LAPACK / ARPACK (the Infomap algorithm uses none of these) so we need to keep on investigating there.

**Comment by vtraag** [comment]
I believe that Informal uses some eigenvector to get the stationary probabilities for a random walk. Presumably that then also relates to some of the external libraries?

**Comment by ntamas** [comment]
Hmmm, you may be right. Nevertheless, I still need to reproduce the issue somehow before I can proceed further. I'll try an i386 chroot somewhere and see if the bug surfaces there.

**Comment by ntamas** [comment]
Managed to reproduce the failures in an i386 chroot. Most of these (the ones that I actually understand) seem to be numerical inaccuracies and/or changes in labeling of clusterings that are semantically equivalent. I'll try to make them pass by modifying the test cases.

**Comment by tillea** [comment]
On Fri, Apr 17, 2020 at 09:30:09AM -0700, Tamás Nepusz wrote:
> Managed to reproduce the failures in an i386 chroot. Most of these (the ones that I actually understand) seem to be numerical inaccuracies and/or changes in labeling of clusterings that are semantically equivalent. I'll try to make them pass by modifying the test cases.
Thanks for this effort and the good news, Andreas.

**Comment by ntamas** [comment]
@tillea All tests pass now on i386 with the recent patches I have committed to the `develop` branch -- these will be merged back to `master` soon as well.

Is there a way to re-run all the tests on the Debian build architecture without making a new upstream release first? Say, if I send you a tarball with these 9 patches, can they be applied in the Debian build process temporarily until we have a new release? We can push this through in a few days if the patches seem to work in the Debian build environment as well.

**Comment by tillea** [comment]
On Mon, Apr 20, 2020 at 07:01:29AM -0700, Tamás Nepusz wrote:
> @tillea All tests pass now on i386 with the recent patches I have committed to the `develop` branch -- these will be merged back to `master` soon as well.
Great.

> Is there a way to re-run all the tests on the Debian build architecture without making a new upstream release first? Say, if I send you a tarball with these 9 patches, can they be applied in the Debian build process temporarily until we have a new release? We can push this through in a few days if the patches seem to work in the Debian build environment as well.
I could use your patch inside the package as `quilt patch` and upload.  This would give us the full matrix of the build architecture failures.

Kind regards
     Andreas.

**Comment by ntamas** [comment]
That's great -- here are the patches: [patches.tar.gz](https://github.com/igraph/igraph/files/4504539/patches.tar.gz).

**Comment by tillea** [comment]
On Mon, Apr 20, 2020 at 08:39:39AM -0700, Tamás Nepusz wrote:
> That's great -- here are the patches: [patches.tar.gz](https://github.com/igraph/igraph/files/4504539/patches.tar.gz).
I'll do my best - but it might be it will take me until tomorrow to apply this.  Thanks a lot in any case, Andreas.

**Comment by tillea** [comment]
On Mon, Apr 20, 2020 at 08:39:39AM -0700, Tamás Nepusz wrote:
> That's great -- here are the patches: [patches.tar.gz](https://github.com/igraph/igraph/files/4504539/patches.tar.gz).
Just uploaded including your patches.  Feel free to observe
   https://buildd.debian.org/status/package.php?p=igraph
in the next couple of hours when the autobuilders will pick the new upload.
Thanks a lot for your cooperation, Andreas.

**Comment by tillea** [comment]
Hi,
as you might have noticed the results became better when considering the number of failed tests but the issue is not solved finally.  I'm attaching the testlog from the i386 build (hmmm, my interface does not like tar - so I use zip :-( )
[tests_log_i386.zip](https://github.com/igraph/igraph/files/4508244/tests_log_i386.zip)
I'll compare with my arm64 (pinebook I just reactivated for this purpose) and let you know about more results.
Kind regards, Andreas.

**Comment by ntamas** [comment]
Okay, this remaining issue will be easy to fix; it is simple a printing issue (the test case prints `-0+0i` instead of `0+0i`). I'll try to fix it in the afternoon.

**Comment by ntamas** [comment]
I'm a bit baffled by this; I have no idea how the test case managed to end up with `-0+0i`, but here's a stab in the dark: https://github.com/igraph/igraph/commit/6fb8f810e6b5aa7a1c8f48a0e86b05afedfd3f17 . I cannot reproduce the issue in my i386 chroot so I don't know whether it would work or not.

**Comment by tillea** [comment]
On Tue, Apr 21, 2020 at 01:31:11PM -0700, Tamás Nepusz wrote:
> I'm a bit baffled by this; I have no idea how the test case managed to end up with `-0+0i`, but here's a stab in the dark: https://github.com/igraph/igraph/commit/6fb8f810e6b5aa7a1c8f48a0e86b05afedfd3f17 . I cannot reproduce the issue in my i386 chroot so I don't know whether it would work or not.
I can only confirm that the test ended up perfectly the same on arm64.  I'll try this patch and let you know.  Thanks for working on this.

**Comment by tillea** [comment]
On Tue, Apr 21, 2020 at 01:31:11PM -0700, Tamás Nepusz wrote:
> I'm a bit baffled by this; I have no idea how the test case managed to end up with `-0+0i`, but here's a stab in the dark: https://github.com/igraph/igraph/commit/6fb8f810e6b5aa7a1c8f48a0e86b05afedfd3f17 . I cannot reproduce the issue in my i386 chroot so I don't know whether it would work or not.

For me it remains:

    cat tests/testsuite.dir/251/testsuite.log 
    #                             -*- compilation -*-
    251. scg.at:71: testing SCG of a graph, stochastic matrix (igraph_scg) : ...
    ./scg.at:73: ${CC} ${CFLAGS} ${abs_top_srcdir}/examples/simple/scg2.c -I${abs_top_srcdir}/include -I${abs_top_builddir}/include -L${abs_top_builddir}/src/.libs -ligraph -lm  -o itest
    ./scg.at:73: cat ${abs_top_srcdir}/examples/'simple/scg2.out' | sed "s/@VERSION@/$(cat ${abs_top_srcdir}/IGRAPH_VERSION)/g" > expout
    ./scg.at:73: 
    ./scg.at:73: DYLD_LIBRARY_PATH=${abs_top_builddir}/src/.libs${DYLD_LIBRARY_PATH+:$DYLD_LIBRARY_PATH} LD_LIBRARY_PATH=${abs_top_builddir}/src/.libs${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH} ./itest
    --- expout      2020-04-22 06:17:00.675501581 +0000
    +++ /build/igraph-0.8.1+ds/tests/testsuite.dir/at-groups/251/stdout     2020-04-22 06:17:00.683501786 +0000
    @@ -47,7 +47,7 @@
     0+0i
     0.316228+0i
     -0.316228+0i
    -0+0i
    +-0+0i
     0.365148+0i
     0.365148+0i
     0.365148+0i
    @@ -109,7 +109,7 @@
     0.316228+0i 0+0i
     0.316228+0i 0.316228+0i
     0.316228+0i -0.316228+0i
    -0.316228+0i 0+0i
    +0.316228+0i -0+0i
     0.316228+0i 0.365148+0i
     0.316228+0i 0.365148+0i
     0.316228+0i 0.365148+0i
    251. scg.at:71: 251. SCG of a graph, stochastic matrix (igraph_scg) : (scg.at:71): FAILED (scg.at:73)

If all else fails we could even simply skip this single test.

**Comment by ntamas** [comment]
Okay, I think I'll just bite the bullet and write a custom matrix printer function for the test cases that replaces all occurrences of `-0+0i`, `-0-0i` and `0-0i` with `0+0i`.

**Comment by szhorvat** [comment]
@ntamas Maybe a macro in the test utilities would help? Something like:

```
#define CANON(x) (x == 0.0 ? 0.0 : x)
```

Then this could be used in all functions that print `double`s to quickly canonicalize results.

**Comment by szhorvat** [comment]
@ntamas  On my machine, `a = -0.0;` then `a + 0.0` results in a positive zero. Tested with `cling`. Maybe that's an even simpler workaround. No `CANON` needed.

**Comment by ntamas** [comment]
I suspect that it won't help here; what probably happens is that we end up with a small value in the real or the imaginary part of the complex number that is smaller than the printing accuracy but larger than the epsilon value that I use to force "small" values to zero. Therefore, the number would not satisfy the `x == 0.0` condition but would nevertheless appear as `0` when printed to stdout. Not sure, though.

**Comment by szhorvat** [comment]
Could be, but I'd expect most tiny numbers to print like `1.23e-300` (big negative exponent). Still, there's a lot of weirdness in floating point implementations, such as denormal numbers.

**Comment by ntamas** [comment]
@tillea I hope this will be the last one: https://github.com/igraph/igraph/commit/ead7e0c59b8bb1745e0e50c892d986f9ccdb7f4f.patch

Can you please try adding this to the patchset? It should explicitly avoid printing `-0` in the test case.

**Comment by tillea** [comment]
On Thu, Apr 23, 2020 at 01:30:22PM -0700, Tamás Nepusz wrote:
> @tillea I hope this will be the last one: https://github.com/igraph/igraph/commit/ead7e0c59b8bb1745e0e50c892d986f9ccdb7f4f.patch
> 
> Can you please try adding this to the patchset? It should explicitly avoid printing `-0` in the test case.

Seems to work.  I'll upload to the autobuilders network soon and will observe
    https://buildd.debian.org/status/package.php?p=igraph
in a couple of hous quickly.
Thanks a lot, Andreas.

**Comment by ntamas** [comment]
Yay, passed everywhere except the `kfreebsd` ones - should we be worried about those? (It is due to missing build deps).

If this is okay, we will release 0.8.2 soon and then Debian can ship an unpatched 0.8.2 release to get the same result.

**Comment by tillea** [comment]
On Fri, Apr 24, 2020 at 07:40:40AM -0700, Tamás Nepusz wrote:
> Yay, passed everywhere except the `kfreebsd` ones - should we be worried about those? (It is due to missing build deps).

Yes, you can not do anything about missing Build-Depends.
 
> If this is okay, we will release 0.8.2 soon and then Debian can ship an unpatched 0.8.2 release to get the same result.

That would be nice.  However, if you plan any more changes - the patches do not really hurt in practice.  So take your time and feel free to close this issue.

Thanks a lot for your support, Andreas.
