### ISSUE TITLE
Error in `igraph_write_graph_dot()`

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2506]
**Describe the bug**

See below.

**To reproduce**

Red the following GraphML file then try to write it back in DOT format:

```xml
<graphml><key id="d3" for="" attr.type="s"></key><key id="d3" for="" attr.type=""></key><graph></graph></graphml>
```

Refer to the `write_all_graphml.cpp` fuzzer for reference.

It gives the error:

```
Error at src/graph/cattributes.c:2577 : Boolean graph attribute expected. - Invalid value.

Stack trace:
    #0 0x10276d9ac in __sanitizer_print_stack_trace+0x28 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x5d9ac)
    #1 0x100f1b008 in igraph_abort error.c:69
    #2 0x100f1ac84 in igraph_error_handler_abort error.c:202
    #3 0x100f1ab68 in igraph_error error.c:171
    #4 0x1010f35d4 in igraph_i_cattribute_get_bool_graph_attr cattributes.c:2577
    #5 0x1010cfc80 in igraph_i_attribute_get_bool_graph_attr attributes.c:246
    #6 0x1011fac64 in igraph_write_graph_dot dot.c:226
    #7 0x100f10688 in LLVMFuzzerTestOneInput write_all_graphml.cpp:65
    #8 0x1013adce8 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) FuzzerLoop.cpp:614
    #9 0x10139b688 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) FuzzerDriver.cpp:324
    #10 0x1013a0670 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) FuzzerDriver.cpp:859
    #11 0x1013c8d1c in main FuzzerMain.cpp:20
    #12 0x182f810dc  (<unknown module>)
    #13 0x560ffffffffffffc  (<unknown module>)
```

**Version information**
`master`

**Comment by szhorvat** [comment]
Would you have time to look at this @ntamas ?

**Comment by ntamas** [comment]
Strictly speaking, the input is not even valid GraphML so we should have rejected it in the first place. I believe that there are two bugs to be fixed here:

- [ ] The input GraphML file should be rejected because of the invalid attribute type.
- [ ] We need to check the internal representation of whatever was loaded into igraph from the GraphML file, check if the data structure is consistent, and if it is, we should figure out why the GML writer thinks that there is a Boolean graph attribute at all.

**Comment by szhorvat** [comment]
This made its way to OSS-fuzz in case some of the info there helps: https://oss-fuzz.com/testcase-detail/6556836276797440 It's okay to have this open for a while there.

**Comment by ntamas** [comment]
Duplicate attribute detection was broken in the GraphML reader; this is now fixed. There's still one bug: `attr.type` is prefix-matched so `attr.type="s"` matches `"string"` and is thus treated as a string attribute, even though it's invalid GraphML. I'll fix this later.

**Comment by szhorvat** [comment]
It looks like we have a very similar issue from the fuzzer, see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67025 Minimization didn't complete, so I'll try to do it locally.

**Comment by szhorvat** [comment]
Here it is: 
[bad2.graphml.gz](https://github.com/igraph/igraph/files/14397283/bad2.graphml.gz)

**Comment by szhorvat** [comment]
What seems to be happening is that the GraphML reader creates a graph with inconsistent attribute records (??)

Then when `write_graph_dot()` accesses it, an error occurs.

Or something like that, I might be wrong. Do you have time to take a look next week @ntamas?

```
Error at src/graph/cattributes.c:2552 : Numeric graph attribute '' expected, got type 3. - Invalid value.

Stack trace:
    #0 0x1045459ac in __sanitizer_print_stack_trace+0x28 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x5d9ac)
    #1 0x102cfd810 in igraph_abort error.c:69
    #2 0x102cfd48c in igraph_error_handler_abort error.c:202
    #3 0x102cfd370 in igraph_error error.c:171
    #4 0x102cfd680 in igraph_errorf error.c:187
    #5 0x102ed3f30 in igraph_i_cattribute_get_numeric_graph_attr cattributes.c:2552
    #6 0x102eb0bf8 in igraph_i_attribute_get_numeric_graph_attr attributes.c:182
    #7 0x102fdd114 in igraph_write_graph_dot dot.c:211
    #8 0x102cf2e90 in LLVMFuzzerTestOneInput write_all_graphml.cpp:65
```

**Comment by ntamas** [comment]
Fixed both in `master` and in `develop`. It was a bug in the trie data structure that allowed an insertion of an empty string but then reported the empty string as not being present in the trie, allowing the duplication of an attribute record for `<key id="">` in GraphML.

**Comment by szhorvat** [comment]
Hm, I just pulled from `master` (I'm on commit 57cd9eb070944dbf2813128f35abc51b468bf988) and I still see the same error, with the same stack trace.

```
Error at src/graph/cattributes.c:2552 : Numeric graph attribute '' expected, got type 3. - Invalid value.

Stack trace:
    #0 0x1027099ac in __sanitizer_print_stack_trace+0x28 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x5d9ac)
    #1 0x100ebfa18 in igraph_abort error.c:69
    #2 0x100ebf694 in igraph_error_handler_abort error.c:202
    #3 0x100ebf578 in igraph_error error.c:171
    #4 0x100ebf888 in igraph_errorf error.c:187
    #5 0x1010962c0 in igraph_i_cattribute_get_numeric_graph_attr cattributes.c:2552
    #6 0x101072f88 in igraph_i_attribute_get_numeric_graph_attr attributes.c:182
    #7 0x10119f4a4 in igraph_write_graph_dot dot.c:211
    #8 0x100eb5098 in LLVMFuzzerTestOneInput write_all_graphml.cpp:65
```

**Comment by ntamas** [comment]
Commit 57cd9eb07 works for me on my machine, both with the minimized and the unminimized test case. Can you post the test case here that fails for you?

**Comment by szhorvat** [comment]
I updated the docs on building fuzzers locally. Can you make it work on your machine? https://github.com/igraph/igraph/wiki/Fuzzing If yes, you may want to add specific commands you use with Homebrew, for later copying.

**Comment by ntamas** [comment]
Okay, so strictly speaking this should be a parse error as well, but it's harder to detect than the previous cases. Right now we have a trie that maps from `<key>` IDs to the corresponding attribute records. The attribute record itself contains the name (from the value of the `attr.name` attribute of the `<key>`) tag, but nothing prevents the user from creating multiple `<key>` tags with different IDs and identical `attr.name` attributes. We then end up with two attribute records for the same attribute name. If we wanted to detect this situation at parse time, we would need another trie that maps attribute _names_ (prefixed by `g` for graph attributes, `v` for vertex attributes and `e` for edge attributes to allow duplicates if they refer to different parts of the graph) to the corresponding attribute records.

But, IMHO, the real bug is not here but in the attribute handler that leaves it unspecified what should happen if the user passes multiple attribute records with the same name to the function responsible for creating the attributes of the graph. If we specified that the attribute handler must anticipate this and check the validity of the input, then the problem could be solved in the attribute handler implementation in C, R, Python and Mathematica. Alternatively, we could specify that passing such an attribute record list yields unspecified behaviour and it is the responsibility of the caller to validate the attribute records -- but then we would need to update all graph readers instead, and any constructors that might create attributes.

I can't really decide yet which one is the better solution -- in my head, shifting the responsibility of validating the input to the higher-level interfaces feels wrong but I'm not 100% convinced yet. I'll get back to this after a good night's sleep or two. Any comments in the meantime @szhorvat ?
