### ISSUE TITLE
community_spinglass with negative weights gives error in pyhton

### ISSUE THREAD

**Issue by ejjordan** [igraph/igraph#825]
I am trying to learn community structure from a correlation matrix, a problem for which the spinglass model is designed. However, I think there is an issue with the C code that python-igraph is calling that prevents negative weights from being used. Here is a minimal example that fails (using python-igraph 0.6.5, I haven't checked if 0.7.0 works for this, but suspect the bug persists). It consists of a simple graph from the Traag & Bruggeman paper where the extension to negative weights is outlined with three nodes, two correlated and one anticorrelated.

```python
adjacency=[[0,1,-1],[1,0,-1],[-1,-1,0]]
small_graf=gp.Graph.Weighted_Adjacency(adj,mode="UPPER",attr='weight')
spinglass=small_graf.community_spinglass(weights=small_graf.es['weight'],implementation='neg')
```

The error that comes up is

```
InternalError: Error at community.c:900: negative weight in weight vector, Invalid value
```

Looking in community.c shows that the modularity function does a check to ensure that all values are positive

```C
if (w < 0)
    IGRAPH_ERROR("negative weight in weight vector", IGRAPH_EINVAL);
```

which I believe is the source of the trouble. I tried just cloning the C igraph library and commenting out these lines, but was unable to get that to work. Additionally, in most other cases, I think that negative weights is not what is wanted so the error is good. Any insight on how to fix this issue, or what I am doing wrong, would be very much appreciated.

**Comment by ntamas** [comment]
This is a bug in the Python interface. The problem lies in the `VertexClustering` object that wraps the "raw" clustering result coming from the C library. As a convenience feature, `VertexClustering` tries to calculate the modularity of the obtained partition, and it freaks out when the modularity function finds the negative edge weights. It has to be fixed in the `VertexClustering` object - as a workaround, you can try modifying `VertexClustering.recalculate_modularity` to handle exceptions from the call to `modularity()` gracefully. I'll come up with a proper fix soon.

**Comment by ntamas** [comment]
Fixed in https://github.com/igraph/python-igraph/commit/60f2552c6e3c355a02f7443149b710c6bebd506e

**Comment by ejjordan** [comment]
At least on my end, this does not fix the issue. The error is still thrown. In addition, this bugfix still does not actually allow for modularity to be calculated, which is important for analysis of results. I am no C programmer, but after a little digging, I think I might have a solution. I just don't know how to implement it. The program community.c (the one which throws the error), has a function to calculate the modularity which cannot tolerate negative weights. In this case, it may be better to catch the return value of the call to ```igraph_i_community_spinglass_negative``` in clustertool.cpp and not allow the ```recalculate_modularity``` python functionality to work. It might even be possible to regain this functionality by wrapping the ```PottsModel::calculate_Q()``` call in pottsmodel_2.cpp in the python layer. Let me know if this makes sense or if you have any advice on how to do this. Thanks!

**Comment by ntamas** [comment]
Discussion moved to https://github.com/igraph/python-igraph/issues/31 as it seems to affect the Python layer only.
